pr: none

trigger:
  paths:
    exclude:
      - docs

variables:
  isMain: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  gradleCacheVersion: v1
  BUILD_VERSION: $(Build.BuildNumber)

stages:
  - stage: check
    jobs:
      - job: check
        steps:
          - template: azure/execute-gradle.yml
            parameters:
              gradleTasks: clean check
              publishJUnitResults: true

#  - ${{ if eq(variables.isMain, true) }}:
  - stage: package
    dependsOn: check
    variables:
      - group: package
    jobs:
      - job: packageUbuntu
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: azure/execute-gradle.yml
            parameters:
              gradleTasks: nativeCompile
          - publish: build/native/nativeCompile/backupr
            name: linux-x64
      - job: packageWindows
        pool:
          vmImage: windows-latest
        steps:
          - template: azure/execute-gradle.yml
            parameters:
              gradleTasks: nativeCompile
              graalVmReleaseItem: windows-x64_bin.zip
          - publish: build/native/nativeCompile/backupr.exe
            name: windows-x64
