pr: none

trigger:
  paths:
    exclude:
      - docs

variables:
  isMain: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  gradleCacheVersion: v1
  BUILD_VERSION: $(Build.BuildNumber)

stages:
  - stage: check
    jobs:
      - job: check
        steps:
          - template: azure/execute-gradle.yml
            parameters:
              useGraal: false
              gradleTasks: clean check
              publishJUnitResults: true

  - ${{ if eq(variables.isMain, true) }}:
      - stage: packageDocker
        dependsOn: check
        pool: self-hosted-scale-set-02
        variables:
          - group: package
          - name: dockerRegistry
            value: stefanpuia.azurecr.io
          - name: dockerImage
            value: backupr
          - name: dockerImageVersion
            value: $(Build.BuildNumber)
        jobs:
          - job: packageDocker
            steps:
              - task: Docker@2
                inputs:
                  command: build
                  repository: $(dockerRegistry)/$(dockerImage)
                  containerRegistry: azureContainerRegistry2-Backupr
                  tags: |
                    $(dockerImageVersion)
                    latest
              - task: Docker@2
                displayName: Login to ACR
                inputs:
                  command: login
                  containerRegistry: azureContainerRegistry2-Backupr
              - task: Docker@2
                displayName: Push image
                inputs:
                  command: push
                  containerRegistry: azureContainerRegistry2-Backupr
                  repository: $(dockerRegistry)/$(dockerImage)
                  tags: |
                    $(dockerImageVersion)
                    latest
              - task: Docker@2
                displayName: Docker Logout
                inputs:
                  command: logout
                  containerRegistry: azureContainerRegistry2-Backupr
                condition: always()

      - stage: packageUbuntu
        dependsOn: check
        pool:
          vmImage: ubuntu-latest
        variables:
          - group: package
        jobs:
          - job: packageUbuntu
            steps:
              - template: azure/execute-gradle.yml
                parameters:
                  gradleTasks: nativeCompile
              - publish: build/native/nativeCompile/backupr
                artifact: linux-x64

      - stage: packageWindows
        dependsOn: check
        pool:
          vmImage: windows-latest
        variables:
          - group: package
        jobs:
          - job: packageWindows
            steps:
              - template: azure/execute-gradle.yml
                parameters:
                  gradleTasks: nativeCompile
                  graalVmReleaseItem: windows-x64_bin.zip
              - publish: build/native/nativeCompile/backupr.exe
                artifact: windows-x64
