spring:
  application:
    name: backupr
    version: 1.1
  main:
    banner-mode: off
    log-startup-info: false
    web-application-type: none
  shell:
    interactive:
      enabled: false
    script:
      enabled: false
    noninteractive:
      primary-command: "${PRIMARY_COMMAND:}"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:}"

logging:
  pattern:
    console: "${LOGGING_PATTERN:%d{yyyy-MM-dd HH:mm:ss} | %-5level | %msg%n}"
  level:
    root: warn
    co.uk.stefanpuia.backupr: warn
    org.jline: error
    com.azure.core.http.netty.implementation.NettyUtility: warn
    com.azure.spring.cloud.core.implementation.util.AzureSpringIdentifier: error
