spring:
  application:
    name: backupr
    version: 1.1
  main:
    banner-mode: off
    log-startup-info: false
    web-application-type: none
  shell:
    noninteractive:
#      primary-command: backup -d -v
      primary-command: validate -v
#    interactive:
#      enabled: true
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:}"

logging:
  level:
    root: warn
    co.uk.stefanpuia.backupr: warn
    org.jline: error
    com.azure.core.http.netty.implementation.NettyUtility: warn
    com.azure.spring.cloud.core.implementation.util.AzureSpringIdentifier: error