[versions]
immutables = "2.10.1"
mapstruct = "1.6.3"
springShell = "3.4.0"
dockerApi = "3.7.1"


[libraries]
azure-bom = { group = "com.azure", name = "azure-sdk-bom", version = "1.2.34" }
azure-identity = { group = "com.azure", name = "azure-identity" }
azure-storage-blob = { group = "com.azure", name = "azure-storage-blob" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.27.1" }
docker-api = { group = 'com.github.docker-java', name = 'docker-java', version.ref = 'dockerApi' }
docker-java-transport-zerodep = { group = 'com.github.docker-java', name = 'docker-java-transport-zerodep', version.ref = 'dockerApi' }
immutables = { group = "org.immutables", name = "value", version.ref = "immutables" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind" }
jackson-dataformat-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310" }
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version = "7.2.1.202505142326-r" }
junit-pioneer = { group = "org.junit-pioneer", name = "junit-pioneer", version = "2.3.0" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
lombok = { group = "org.projectlombok", name = "lombok" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
slf4j-test = { group = "com.github.valfirst", name = "slf4j-test", version = "3.0.1" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-shell-dependencies = { group = "org.springframework.shell", name = "spring-shell-dependencies", version.ref = "springShell" }
spring-shell-starter = { group = "org.springframework.shell", name = "spring-shell-starter" }
spring-shell-starter-test = { group = "org.springframework.shell", name = "spring-shell-starter-test" }
spring-web = { group = 'org.springframework', name = 'spring-web' }
string-template = { group = "org.antlr", name = "ST4", version = "4.3.4" }


[plugins]
dotenv = { id = 'co.uzzu.dotenv.gradle', version = '4.0.0' }
graal-build-tools = { id = 'org.graalvm.buildtools.native', version = '0.10.6' }
spotless = { id = 'com.diffplug.spotless', version = '7.0.3' }
spring-boot = { id = "org.springframework.boot", version = "3.4.5" }
spring-dependency = { id = 'io.spring.dependency-management', version = '1.1.7' }


[bundles]
docker = ['docker-api', 'docker-java-transport-zerodep']
jackson = ['jackson-databind', 'jackson-dataformat-xml', 'jackson-datatype-jsr310']
